#!/usr/bin/perl;
##################################################
#
# Perl::Tk script generated by Visual Camel 0.0.2.2
#
##################################################
use warnings;
use strict;
use Tk;

my $mw = MainWindow->new( -width => '640', -relief => 'flat', -height => '480', );
my $var1 = $mw->Entry( -width => '20', -relief => 'sunken', -state => 'normal', -justify => 'left', )->place( -x => 16, -y => 93);
my $var2 = $mw->Label( -pady => '1', -relief => 'flat', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Instance', )->place( -x => 13, -y => 26);
my $var3 = $mw->Label( -pady => '1', -relief => 'flat', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Schema', )->place( -x => 13, -y => 44);
my $var4 = $mw->Button( -pady => '1', -relief => 'raised', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Testify station', )->place( -x => 149, -y => 92);
my $var5 = $mw->Label( -pady => '1', -relief => 'flat', -padx => '1', -state => 'normal', -justify => 'center', -text => 'Label2', )->place( -x => 12, -y => 64);
my $var6 = $mw->Button( -pady => '1', -relief => 'raised', -padx => '1', -state => 'normal', -justify => 'center', -text => 'START_FSTA', )->place( -x => 18, -y => 137);
my $var7 = $mw->Button( -pady => '1', -relief => 'raised', -padx => '1', -state => 'normal', -justify => 'center', -text => 'EXIT', )->place( -x => 19, -y => 166);

$mw->MainLoop();
##################################################
#
# Perl::Tk script generated by Visual Camel 0.0.2.2
#
##################################################
